import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { DynamicBackground } from "@/components/background";
import { QueryProvider } from "@/components/providers/QueryProvider";

import "./globals.css";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="ru"
			className={`${inter.variable} h-full antialiased`}
			data-glassmorphism="dark"
		>
			<body className="min-h-full flex flex-col">
				<QueryProvider>
					<DynamicBackground />
					<div id="app-root" className="flex min-h-full flex-1 flex-col">
						{children}
					</div>
				</QueryProvider>
			</body>
		</html>
	);
}
